package com.bhg.posServer.utils;

public interface Constants {
	
	String WXMOVIE_DATABASE = "wxmovie_v4";
	
	String CORE_DATABASE = "wxmovie_core_v2";
	
	String REDIS_KEY_ADVERTISEMENT_PV = "ADVERTISEMENT_PV";
	
	String REDIS_KEY_ADVERTISEMENT_PV_FRAME = "ADVERTISEMENT_PV_FRAME";
	
	String REDIS_KEY_ADVERTISEMENT_CLICK = "ADVERTISEMENT_CLICK";
	
	String REDIS_KEY_ADVERTISEMENT_CLICK_FRAME = "ADVERTISEMENT_CLICK_FRAME";
	
	String REDIS_KEY_ADVERTISEMENT_UV = "AD_UV";

	String REDIS_KEY_ADVERTISEMENT_UV_FRAME = "AD_UV_FRAME";
	
	String REDIS_KEY_ADVERTISEMENT_CITY_PV = "ADVERTISEMENT_CITY_PV";
	
	String REDIS_KEY_ADVERTISEMENT_CITY_CLICK = "ADVERTISEMENT_CITY_CLICK";
	
	String REDIS_KEY_ADVERTISEMENT_CITY_UV = "AD_CITY_UV";
	
	String REDIS_KEY_ADVERTISEMENT_MOVIE_CINEMA_PV = "ADVERTISEMENT_MOVIE_CINEMA_PV";
	
	String REDIS_KEY_ADVERTISEMENT_MOVIE_CINEMA_CLICK = "ADVERTISEMENT_MOVIE_CINEMA_CLICK";
	
	String REDIS_KEY_ADVERTISEMENT_MOVIE_CINEMA_UV = "AD_MC_UV";
	
	String REDIS_KEY_MATERIAL_PV = "MATERIAL_PV";
	
	String REDIS_KEY_MATERIAL_CLICK = "MATERIAL_CLICK";
	
	String REDIS_KEY_MATERIAL_UV = "MATERIAL_UV";
	
	String REDIS_KEY_MATERIAL_CITY_PV = "MATERIAL_CITY_PV";
	
	String REDIS_KEY_MATERIAL_CITY_CLICK = "MATERIAL_CITY_CLICK";
	
	String REDIS_KEY_MATERIAL_CITY_UV = "MATERIAL_CITY_UV";
	
	String PARAM_ADVERTISEMENT_UUID = "advertisementUuid";
	
	String PARAM_ITEMID = "itemId";
	
	String PARAM_UUID = "uuid";
	
	String PARAM_MATERIAL_ID = "materialId";

	String PARAM_CITY = "city";
	
	String PARAM_CITY_NAME = "cityName";
	
	String PARAM_CINEMA_ID = "cinemaId";
	
	String PARAM_MOVIE_ID = "movieId";
	
	String PARAM_USER_AGENT = "ua";
	
	String FRAME_ID = "frame";

}
